### ISSUE TITLE
activation error

### ISSUE THREAD

**Issue by larshp** [BTCAG/Featuretoggle#3]
Hi,
Structure ZSY_FEATUREREFERENCE uses 2 data elements from namespace /EAS/, guess these have to be replaced with the "Z_" data elements?

![image](https://cloud.githubusercontent.com/assets/5888506/26778500/cfee8868-49e1-11e7-8e5f-92183f82cf43.png)

**Comment by BTCAG** [comment]
Hi larshp,

thanks for the response. Yes you are correct, we will fix this asap.

Best regards

**Comment by BTCAG** [comment]
Commit #59121eb62e7ccd4af2f73df6a28f096198a0686e should fix this issue.
